### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by AdityaNahata** [Jiganesh/Code_Trek#1]
How many projects would you recommend to build while learning? And what should be the difficulty level of each project (like mini projects etc)?
Btw awesome journey and have a great career ahead!

**Comment by Jeevan-23** [comment]
Nice

**Comment by Jiganesh** [comment]
Hello @Jeevan-23  @ImThorThunderGod , Thanks 
Answering your question I would say you should have 2 or maximum 3 projects, not more than that. Regarding level of project you should keep it as good as you can. Better projects get more preference. summarizing what I said - build 2-3 great project in your niche.
